name: List Changed Files in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: Fetch base branch and list changed files
        run: |
          git fetch origin main
          echo "Changed files:"
          git diff --name-only origin/main...HEAD > changed_files.txt
          cat changed_files.txt

      - name: Upload changed files (optional)
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed_files.txt
