name: check-md-changes

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-deph: 0
        

      - name: Check for changes in .md file
        run: git fetch origin main
          echo "Changed Files:"
          git diff --name-only origin/main...HEAD > changed_files.txt
          cat changed_files.txt 
            
